// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpIMQdrowzBFNeUYfZAsjehRpq-EyH97E',
    appId: '1:438858541121:web:f5f10ea068048e7cb53ec0',
    messagingSenderId: '438858541121',
    projectId: 'zero-pls-cf676',
    authDomain: 'zero-pls-cf676.firebaseapp.com',
    storageBucket: 'zero-pls-cf676.appspot.com',
    measurementId: 'G-1T9DTTK5KL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKDMocCLxvT7D4yHDMe0TRDV-8e6lbZx4',
    appId: '1:438858541121:android:047dab7e10693855b53ec0',
    messagingSenderId: '438858541121',
    projectId: 'zero-pls-cf676',
    storageBucket: 'zero-pls-cf676.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASEmcju52BHqClPi781JaD3Xh-spw9ZVE',
    appId: '1:438858541121:ios:524839ba7e3f45ceb53ec0',
    messagingSenderId: '438858541121',
    projectId: 'zero-pls-cf676',
    storageBucket: 'zero-pls-cf676.appspot.com',
    iosBundleId: 'com.example.zeroPls',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASEmcju52BHqClPi781JaD3Xh-spw9ZVE',
    appId: '1:438858541121:ios:524839ba7e3f45ceb53ec0',
    messagingSenderId: '438858541121',
    projectId: 'zero-pls-cf676',
    storageBucket: 'zero-pls-cf676.appspot.com',
    iosBundleId: 'com.example.zeroPls',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDpIMQdrowzBFNeUYfZAsjehRpq-EyH97E',
    appId: '1:438858541121:web:8d745986518bf0c3b53ec0',
    messagingSenderId: '438858541121',
    projectId: 'zero-pls-cf676',
    authDomain: 'zero-pls-cf676.firebaseapp.com',
    storageBucket: 'zero-pls-cf676.appspot.com',
    measurementId: 'G-Z82CZ9S5CB',
  );

}